export enum tweetsConstant {
    TWEETS_HAS_ERRORED = 'TWEETS_HAS_ERRORED',
    TWEETS_IS_LOADING = 'TWEETS_IS_LOADING',
    TWEETS_FETCH_DATA_SUCCESS = 'TWEETS_FETCH_DATA_SUCCESS',

    TWEETS_ADD = 'TWEETS_ADD', 
    ADD_TWEET_SUCCESS = 'ADD_TWEET_SUCCESS',
    ADD_TWEET_FAILURE = 'ADD_TWEET_FAILURE',
    
    SEARCH_USERS = 'SEARCH_USERS',
    USERS_FETCH_DATA_SUCCESS = 'USERS_FETCH_DATA_SUCCESS',

    LIKE_SUCCESS = 'LIKE_SUCCESS',
    LIKE_FAILURE = 'LIKE_FAILURE',

    UNLIKE_SUCCESS = 'UNLIKE_SUCCESS',
    UNLIKE_FAILURE = 'UNLIKE_SUCCESS',

    RENDER_TWEET_SUCCESS = 'RENDER_TWEET_SUCCESS',
    RENDER_TWEET_FAILURE = 'RENDER_TWEET_FAILURE',
}
export default tweetsConstant;