export enum userConstants {
    INITIAL_STATE = 'INITIAL_STATE',
    LOGIN_REQUEST = 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE = 'USERS_LOGIN_FAILURE',
    AUTH_ISLOADING = 'AUTH_ISLOADING',

    LOGOUT = 'USERS_LOGOUT',

    REGISTER_REQUEST = 'REGISTER_REQUEST',
    REGISTER_SUCCESS = 'REGISTER_SUCCESS',
    REGISTER_FAILURE = 'REGISTER_FAILURE',

    USER_SUBSCRIBE = 'USER_SUBSCRIBE',

    USER_RETWEETED = 'USER_RETWEETED',
    USER_UNRETWEETED = 'USER_UNRETWEETED',
}
export default userConstants;