export enum userConstants {
    LOGIN_REQUEST = 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE = 'USERS_LOGIN_FAILURE',

    LOGOUT = 'USERS_LOGOUT',

    REGISTER_REQUEST = 'REGISTER_REQUEST',
    REGISTER_SUCCESS = 'REGISTER_SUCCESS',
    REGISTER_FAILURE = 'REGISTER_FAILURE',

    USER_SUBSCRIBE = 'USER_SUBSCRIBE',

    USER_RETWEETED = 'USER_RETWEETED'
}
export default userConstants;