export const tweetsConstant = {
    FETCH_TWEETS_STARTED: 'FETCH_TWEETS_STARTED',
    FETCH_TWEETS_REJECTED: 'FETCH_TWEETS_REJECTED',
    FETCH_TWEETS_FULFILLED: 'FETCH_TWEETS_FULFILLED',

    FETCH_USER_TWEETS_STARTED: 'FETCH_USER_TWEETS_STARTED',
    FETCH_USER_TWEETS_REJECTED: 'FETCH_USER_TWEETS_REJECTED',
    FETCH_USER_TWEETS_FULFILLED: 'FETCH_USER_TWEETS_FULFILLED',

    POST_TWEET_STARTED: 'POST_TWEET_STARTED',
    POST_TWEET_SUCCESS: 'POST_TWEET_SUCCESS',
    POST_TWEET_FAILED: 'POST_TWEET_FAILED',
}