export const userConstants = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    REGISTER_REQUEST: 'USERS_GETALL_REQUEST',
    REGISTER_SUCCESS: 'USERS_GETALL_SUCCESS',
    REGISTER_FAILURE: 'USERS_GETALL_FAILURE'
};